
default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: dojo_secrets_development

test:
  <<: *default
  database: dojo_secrets_test


production:
  <<: *default
  database: dojo_secrets_production
  password: <%= ENV['DOJO_SECRETS_DATABASE_PASSWORD'] %>
