# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5c3f4a9a87cb032dc816307588a1d05aa506a59f2fce691e19201369bbb7bfa2e94af2671f9fcd595af1ba0321fbf4f433408751808f75b42ec76198e4c8e74

test:
  secret_key_base: 8c9dc5503daa3e6bc47bbf8bc5450a79ddca86fbe529160896c9dd4240a261017700fa0a8a7d4de9b6d506be8c8ca55c461ac11eb9f69b1f7e37fea1d9e98437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
